FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/Varvarin-Mud-Plus.Web/out/ .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Varvarin-Mud-Plus.Web.dll"]